### ISSUE TITLE
Preview - Videos Crash the application on Windows

### ISSUE THREAD

**Issue by sedouard** [azure-storage/xplat#109]
Playing an mp4 video crashes the application on windows. Most likely due to something wrong with the ffmpeg binary, either module not found or something else. Probably have to use a windows debugger to understand what's happening.

**Comment by felixrieseberg** [comment]
Have we ever figured out what's actually going on there?

**Comment by sedouard** [comment]
nope haven't hat cycles to look at it

**Comment by cicorias** [comment]
were @sedouard were you able you grab any stack trace or event log wntries

**Comment by felixrieseberg** [comment]
Actually, this is fixed with the introduction of Electron.
