### ISSUE TITLE
Folder Creation during Upload

### ISSUE THREAD

**Issue by felixrieseberg** [azure-storage/xplat#113]
We can "create" folders by defining the path a blob is being uploaded to. When we create a new folder, that folder isn't immediately loaded.

### Reproduction
 * Upload a blob
 * Add a new folder to the blob's path
 * Click 'upload'
 * Your new folder won't appear until you reopen the container

**Comment by sedouard** [comment]
clsoed via https://github.com/azure-storage/xplat/commit/2a65f96bc7913646655b578aadc0815a0846136f
