### ISSUE TITLE
Minor - Lock or relocate breadcrumbs

### ISSUE THREAD

**Issue by stefangordon** [azure-storage/xplat#137]
I've got folders with a few hundred thousand blobs in them.  It takes me a long time to scroll to the bottom and see the last one, and then when I want to go up a directory I have to scroll waaaaay back up to get to the breadcrumb.  My scrolling finger is tired :)

A variety of things could make this better.  Breadcrumb could be locked so it is always visible rather than scrolling.  You could also just have a scroll bar so I can go back up easily.

**Comment by stefangordon** [comment]
Is it possible you broke scrolling when you did this?

**Comment by felixrieseberg** [comment]
Yes, very possible. Let me quickly do a hotfix :)

**Comment by felixrieseberg** [comment]
...and unbroken. A css line didn't make it into the commit, but it's working now. Thanks!
