### ISSUE TITLE
Can only upload once

### ISSUE THREAD

**Issue by stefangordon** [azure-storage/xplat#138]
The upload functionality appears to be single use.  

1.  Go to a folder
2. Upload a text file -> works
3. Go to another folder
4. Upload a text file -> nothing happens

Restarting the application lets me upload another file.

**Comment by stefangordon** [comment]
New info - It appears this may only happen when uploading the same file in multiple places.

**Comment by felixrieseberg** [comment]
Thanks dude, you testing this is a lifesaver. At the same time: Wtf. @sedouard: That's probably us, right? Without looking at code, sounds like the blob controller doesn't clean up after itself.

**Comment by sedouard** [comment]
Thanks stefan. Looks like it has to do with the [nwInput.change](https://github.com/azure-storage/xplat/blob/master/app/controllers/explorer.js#L190) handler not being fired. Probably because... well nothing's changed. Let me look up if theres another hook from nw we can use.

**Comment by stefangordon** [comment]
Ah yeah, or maybe you can clear it after the upload happens.

**Comment by sedouard** [comment]
closed via https://github.com/azure-storage/xplat/commit/b0645bb16efa12a0d89caea8f6927fb532748d19
