### ISSUE TITLE
Contributing Guide 

### ISSUE THREAD

**Issue by felixrieseberg** [azure-storage/xplat#156]
We should have a contributing guide. I'm not sure that we'll need it right away, but I'd like to make sure that nobody is turned away because we don't have one, event if it's a simple one.

**Comment by sedouard** [comment]
+1. I've been thinking about this on the side. Honestly I really like engine yards contributing guide for [deis](https://github.com/deis/deis/blob/master/CONTRIBUTING.md) covers how to do the commits, naming conventions and even suggests commit convention.
