### ISSUE TITLE
Notifications: Test Controller

### ISSUE THREAD

**Issue by felixrieseberg** [azure-storage/xplat#160]

**Comment by sedouard** [comment]
I think this should be something implicit. Add functional features to Notifications controller, you add a test for it. Otherwise I'm not sure when this issue would be closed.

**Comment by felixrieseberg** [comment]
You're totally right - I just wanted to make sure that you take a look at what I merged before writing the tests for it. Pending your "this is not horrible", it's literally the next thing I'll do :)
