### ISSUE TITLE
Have some fun, refactor the explorer controller!

### ISSUE THREAD

**Issue by felixrieseberg** [azure-storage/xplat#177]
CodeClimate isn't wrong, the complexity of the explorer controller has gone up quite a bit (https://codeclimate.com/github/azure-storage/xplat/app/controllers/explorer.js).

Once we get a bit of breathing room, we should refactor some things out. The code is *good*, but it could be more human-friendly.

**Comment by sedouard** [comment]
Yeah I noticed this on the last commit, the number keeps going down. I
didn't even know what code climate was but taking a look at it it looks not
totally wrong lol.

On Tuesday, July 7, 2015, Felix Rieseberg <notifications@github.com> wrote:

> CodeClimate isn't wrong, the complexity of the explorer controller has
> gone up quite a bit (
> https://codeclimate.com/github/azure-storage/xplat/app/controllers/explorer.js
> ).
>
> Once we get a bit of breathing room, we should refactor some things out.
> The code is *good*, but it could be more human-friendly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/azure-storage/xplat/issues/177>.
>


-- 
Steven Edouard
Computer Engineering, Undergraduate
Email: sedouard@ufl.edu
Mobile: 4079638488

**Comment by felixrieseberg** [comment]
I'm gonna close this as "good enough", I think all the methods in the controller right now are rightfully there.
