### ISSUE TITLE
Write documentation for Azure.com

### ISSUE THREAD

**Issue by felixrieseberg** [azure-storage/xplat#195]

**Comment by felixrieseberg** [comment]
Update: Sent this over to the Azure content team, but they don't seem super excited right now (https://github.com/Azure/azure-content/pull/4105).

cc @sedouard @ritazh

**Comment by tamram** [comment]
Hey Felix -

We can't publish your article to azure.com because we can't promote tools on our official storage documentation site that the storage team does not support themselves.

For this reason, we need to close your PR.

Tamra
