### ISSUE TITLE
Copy Blob

### ISSUE THREAD

**Issue by sedouard** [azure-storage/xplat#201]

**Comment by sedouard** [comment]
@ritazh said she really wants this. So I told her to build it -- and she said yes. Feel free to reach out to either of us for guidance!

**Comment by felixrieseberg** [comment]
![](http://media.giphy.com/media/7ju6mxgTagFna/giphy.gif)

Go @ritazh! Yeah, totally happy to help you getting started with the codebase.

**Comment by ritazh** [comment]
This has been implemented with #264

**Comment by sedouard** [comment]
closed via https://github.com/azure-storage/xplat/commit/94fa29dbce81fc1fd2c11124013ceee96b67a54e
