### ISSUE TITLE
Inputs not cleared when adding multiple storage accounts (OS X 0.4.0)

### ISSUE THREAD

**Issue by andydoyle** [azure-storage/xplat#209]
When adding multiple storage accounts, the Storage Account Name and Storage Account Key inputs are not cleared and will display the values for the last storage account that was added.

Repro steps:

1. Add a new storage account.
2. When on the main page listing the contents of the storage account, click the logo in the top right of the window to go back to the  storage account selection screen.
3. Click the Add button.
4. Observe that the two inputs on this screen show the name and key of the account you added in step 1.

Thanks.

**Comment by sedouard** [comment]
@laurentran can you look at this

**Comment by felixrieseberg** [comment]
![](http://media.giphy.com/media/oobNzX5ICcRZC/giphy.gif)

**Comment by sedouard** [comment]
closed via https://github.com/azure-storage/xplat/commit/61123a35cfc94301e7bf71ac7810871b925fe429
