### ISSUE TITLE
Create Container button allows to create unnamed or identical named containers

### ISSUE THREAD

**Issue by serhatakinci** [azure-storage/xplat#210]
Effect of this case is not reflected to the Azure Storage service side, but appears in the Container list of Azure Storage Explorer until you restart the application.

![ase2](https://cloud.githubusercontent.com/assets/13350823/8705802/af887cc8-2b34-11e5-99a9-b422e75144e8.PNG)

**Comment by sedouard** [comment]
looks like we generally need to solve some issues with backend resolution. https://github.com/azure-storage/xplat/issues/241.
