### ISSUE TITLE
Improve UI icon for Storage Account Key

### ISSUE THREAD

**Issue by andydoyle** [azure-storage/xplat#212]
Sorry if I'm missing something or interpreting the icon wrongly, but the icon displayed next to Storage Account Key when adding or editing a connection looks like a telephone handset.

An icon of a key would be better in my eyes.

Thanks.

**Comment by felixrieseberg** [comment]
Thanks a lot! You are *very* correct. @sedouard actually caught that a few minutes ago (#211), I'm closing this one as  a duplicate.
