### ISSUE TITLE
Blob list: Action column header representation

### ISSUE THREAD

**Issue by andydoyle** [azure-storage/xplat#213]
It is quite common for the header of a checkbox column to contain an unchecked checkbox so that it is clear that clicking on it will bulk check all items in the column. This would toggle to a checked checkbox when all items in the list were selected.

Displaying "Action" doesn't shout out to me that I can select all items quickly. Displaying the text initially made me think that clicking it would sort the column.

Thanks.

**Comment by felixrieseberg** [comment]
That's a great suggestion - we'll implement that in the next version.
