### ISSUE TITLE
When a new container has been created, the change is not propagated to the backend. 

### ISSUE THREAD

**Issue by ritazh** [azure-storage/xplat#241]
Env:
OSX 10.10.3

Last commit:
f33b61ac6464f96d69c1c2de21fe9ca9010c2dfc

Built locally with "grunt compile"

Repro steps:
1. Login to welcome screen
2. Click "Add Container" button from the top right
3. Create container, put a simple name like "ASETest1"
4. Once it's created, a new container "ASETEST1" is visible on the left pane
5. Close the app
6. Relaunch the app
7. Login to welcome screen
8. New container does not exist

**Comment by ritazh** [comment]
@felixrieseberg @sedouard 
I think the container name needs to be all lower case. This may be confusing when the container names are all converted to upper case in the left pane of the app. 
```
All letters in a container name must be lowercase.
```
http://blogs.msdn.com/b/jmstall/archive/2014/06/12/azure-storage-naming-rules.aspx

**Comment by ritazh** [comment]
@felixrieseberg @sedouard I can work on this bug and #210.

**Comment by sedouard** [comment]
:+1:

**Comment by ritazh** [comment]
This issue has been resolved with #264
