### ISSUE TITLE
Regression: Go Home Broken

### ISSUE THREAD

**Issue by sedouard** [azure-storage/xplat#242]
Appears that the return to home functionality is broken. We should add an integration (ui) test for this as its a pretty basic feature that should always work.

`Selectedblob` is getting cleared and the `ax-preview` component is attempting to read from it.

**Comment by felixrieseberg** [comment]
You sure? I can't reproduce.

**Comment by sedouard** [comment]
Grab the dev build, select a blob, then try to go back home. Should gripe about the preview component trying to run `getLink` on a blob.
