### ISSUE TITLE
Improve Test Code Quality

### ISSUE THREAD

**Issue by felixrieseberg** [azure-storage/xplat#257]
<img width="704" alt="screen shot 2015-07-30 at 10 11 56 am" src="https://cloud.githubusercontent.com/assets/1426799/8989824/714a5d94-36a3-11e5-852a-4d4b386b731a.png">

**Comment by sedouard** [comment]
this is is a regression caused by the blob properties feature I added. Happy to fix it @felixrieseberg

**Comment by felixrieseberg** [comment]
Nah, I'm already on it - it's mostly just grown duplication.
