### ISSUE TITLE
Regression: App doesn't work

### ISSUE THREAD

**Issue by sedouard** [azure-storage/xplat#271]
Dev builds are broken. Nothing pops up at all.

**Comment by felixrieseberg** [comment]
NW.js is throwing a fit about not being able to require modules. It's weird, but I'll figure it out.

**Comment by sedouard** [comment]
delete your `dist` and `tmp` folders. rebuild the app and notice that the `content-for` tags for broccoli never execute for our `index.html`. This leaves out `shim-head.js` and `shim-footer.js` from our app causing the issue we're seeing. as for why its not running thats another issue. Its not specific to just prod builds its actually for dev too.

**Comment by felixrieseberg** [comment]
Fixed it. I'll send a PR in a second.

**Comment by sedouard** [comment]
that issue is fixed but the app is still broken.

**Comment by felixrieseberg** [comment]
I can't reproduce. Are you sure you downloaded the latest build? I just downloaded it again and it works just fine.

**Comment by ritazh** [comment]
Same here...I am not able to start the app with the latest dev build.

**Comment by sedouard** [comment]
Okay the issue is basically with just old local storage hanging around. @ritazh this is probably the issue with yours, too. closing this one out. thanks @felixrieseberg!
