### ISSUE TITLE
Should make account url editable

### ISSUE THREAD

**Issue by kesyn** [azure-storage/xplat#278]
In China, Azure Storage Service has different domain postfix, like [accountname].blob.core.chinacloudapi.cn, so if we can change the whole blob url that your product can also run in China.

**Comment by sedouard** [comment]
Thanks @kesyn, we actually weren't aware of that! Thanks for letting us know and we'll include that.

**Comment by ritazh** [comment]
I will take this one.

**Comment by sedouard** [comment]
thanks @ritazh!

**Comment by felixrieseberg** [comment]
I will tackle this with Tracey.

**Comment by felixrieseberg** [comment]
Hey @kesyn, we now have a build that allows you to change the DNS suffix (thanks to @traceyt!). Would you mind giving it a go? Simply download the "Development Build" on http://storageexplorer.com.

I'll be closing this in the meantime, but feel free to get in touch again if there's something else we could do for Azure China!
