### ISSUE TITLE
Need set permissions on files

### ISSUE THREAD

**Issue by kesyn** [azure-storage/xplat#280]
I'm using Mac(latest beta version OS), when I upload files to containers, I cannot access them from browser(works on Windows), and found the files have no read permissions. If this is a bug, I advise you to add a function that we can set the permissions on files if we need.

**Comment by sedouard** [comment]
Hey kesyn. You'll probably need to change your container permission settings. Can you right-click on the container and set the permissions level from 'OFF' to 'CONTAINER'? Otherwise, right click on the blob, go to properties and generate a shared URL under the 'SAS' tab.

**Comment by kesyn** [comment]
So there is a function on your app that can change permission settings or I have to change it in Azure Portal? I'm trying to right click on it, it just come with "cut copy paste", I mean you can add this function to your application. I am now using an another application named "Cyberduck", it can add permissions. I think there're some functions you can learn from Cyberduck, e.g. Sync files, create directories(not just fill with path), change meta data; set permissions, view info(e.g. url), create archive, copy and open url(Http, Https, and Signed Url).

**Comment by sedouard** [comment]
`I'm trying to right click on it, it just come with "cut copy paste"`

If you use the current development build (version `c5695191487ad76d4564cd0e450161fa78dd2edb`) you can right click on a blob and go to its properties. Then under the SAS link you can get a link with the selected permission.

Checkout the documentation on azure storage:
https://azure.microsoft.com/en-us/documentation/articles/storage-manage-access-to-resources/

You can only set permissions on blobs at the container level, individual blob permissions are managed by Shared Access Signatures.

Thanks for the tips on the features! Most of what you mentioned will be in our next release coming soon.
