### ISSUE TITLE
Need to handle bad storage url

### ISSUE THREAD

**Issue by traceyt** [azure-storage/xplat#283]
If for some reason the url is bad and it is the first time a storage account is selected then the app just hangs.  This is a problem if we allow people to specify their own suffix ie, core.windows.net etc
If it is the 2nd or more storage account selected then the previous account's blobs and containers are shown.  If I throw an error then this prevents the app from proceeding but is not the elegant solution.  Need to clear blobs and containers from the previous selection.

**Comment by sedouard** [comment]
Let's go for a drop down list and not allow the user to enter an arbitrary url. Sounds like that'll keep this from being an issue?

**Comment by traceyt** [comment]
Good idea.  I have sent you all a pull request with the suggested changes and tests.

**Comment by sedouard** [comment]
closed via https://github.com/azure-storage/xplat/commit/a6ff083bf51a5eadb023aabbd6bb6fc7d7291d8c
