### ISSUE TITLE
UPDATE CONTRIBUTING.md regarding Chromium DevTools

### ISSUE THREAD

**Issue by traceyt** [azure-storage/xplat#284]
Update the following...
To get access to the Chromium Developer Tools, simply make a right click and select 'DevTools' - we're also pulling down the Ember Inspector, which can also be launched with a right click.

The right click does not work but the tools are accessible via the help menu.

**Comment by sedouard** [comment]
This is the behavior seen for locally built versions (using `grunt compileDevBuild`), automated dev builds (built off of the tip of master and linked to [storageexplorer.com](http://storageexplorer.com)) and release builds.

If you observed this behavior by running the app with `ember nw` it's a bug. It appears though from my local setup `ember nw` allows for right click -> 'Dev Tools'. (this is controlled by the environment flags used when building)
