### ISSUE TITLE
Loading Indications & Performance

### ISSUE THREAD

**Issue by felixrieseberg** [azure-storage/xplat#62]
Whenever things take a while to load, the experience is really bad - I'll mark this as a bug, because we should directly respond to user input and say "yep, we're getting your information".

We might even want to prefetch data where applicable.

**Comment by stefangordon** [comment]
+1, for large blob lists it takes a while and there is no indicator.  FWIW it takes the same amount of time to load my large blob lists in the commercial CloudBerry explorer, but they do provide load indicators as well as display results in chunks as they come in (1000 blobs at a time or something).

**Comment by sedouard** [comment]
good to know. actually we aren't really using any continuation tokens at the moment under the hood. so the app will inherently not load everything for extremely large accounts. opened https://github.com/azure-storage/xplat/issues/136 to track the issue.

**Comment by sedouard** [comment]
Part of https://github.com/azure-storage/xplat/issues/150

**Comment by sedouard** [comment]
@felixrieseberg looks like we're getting close...
https://youtu.be/AQl4KGT499o

Not crazy about how the progress bar styling looks for < 50%. It isn't clear what the progress is. Also, I can't seem to figure out what `timestamp` wants. Is it milliseconds, is it `new Date()` is it the ISO formatted date? I tried a bunch but couldn't figure out what the `ago` helper is doing in the template.

**Comment by felixrieseberg** [comment]
Timestamp is just Date.now(). I'm also not crazy about the indicator, a good idea would be worth gold. I'd like to keep it around though until we have something better...

**Comment by sedouard** [comment]
closed via https://github.com/azure-storage/xplat/commit/314140e470fa929a523aa58924244f4370f92330
