### ISSUE TITLE
Display folders rather than flattening all blobs

### ISSUE THREAD

**Issue by stefangordon** [azure-storage/xplat#80]
For containers meant to be viewed via GUI tools like this, people often use folders to group files so that enumerating thousands of items isn't required.

**Comment by sedouard** [comment]
@felixrieseberg: 

what do you y'all think about this experience? Its not as good as a tree view obviously but we can certainly do that later (probably would require a custom table control).

https://onedrive.live.com/redir?resid=4D3C1D52A63C3B3B!38922&authkey=!AKvNlCxJPr__uqg&ithint=video%2cmov

**Comment by felixrieseberg** [comment]
Oh wow, that is sexy. I hate how buttons look (it's just materialize), but I'm happy to fix that. Let's merge that, I fix the buttons, and we cut another release?

![](http://media.giphy.com/media/gbbZL8JOuHWDu/giphy.gif)

**Comment by sedouard** [comment]
Need another day for unit testing and code cleanup  but yeah I agree the
buttons suck if you can help there that'd be awesome.

**Comment by stefangordon** [comment]
This is exactly what it needed!

**Comment by sedouard** [comment]
closed via https://github.com/azure-storage/xplat/commit/cfd76c34ed417435aee76550f25a459afc442af6
